version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing .NET dependencies...
      - dotnet restore ASWebApp/ASWebApp.csproj

  build:
    commands:
      - echo Building the project...
      - dotnet publish ASWebApp/ASWebApp.csproj -c Release -o ./output

artifacts:
  files:
    - '**/*'
  base-directory: ./output
  discard-paths: no
