name: Deploy to AWS S3 via CodeBuild

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip the code
      run: |
        zip -r app.zip . -x ".git/*" ".vscode/*" "node_modules/*" "bin/*" "obj/*"

    - name: Upload only app.zip via AWS CLI
      run: aws s3 cp app.zip s3://${{ vars.AWS_BUCKET }}/source/app.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}

    - name: Start AWS CodeBuild Project
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: ${{ vars.AWS_CODE_BUILD_PROJECT_NAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}

    - name: Refresh Auto Scaling Group (replace EC2s)
      run: |
        aws autoscaling start-instance-refresh \
          --auto-scaling-group-name ${{ vars.AWS_ASG_NAME }} \
          --strategy Rolling
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ vars.AWS_REGION }}